# Generated by Django 3.1.5 on 2021-01-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoll.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoll.poll')),
            ],
        ),
        migrations.AlterField(
            model_name='option',
            name='position',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoll.poll')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopoll.answer')),
            ],
        ),
    ]
