# Generated by Django 3.1.5 on 2021-01-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinopoll', '0003_response_poll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['id']},
        ),
    ]
